apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: cron
spec:
  schedule: "* * * * *"
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: cron
    uri: /